#!/usr/bin/env bash
set -eo pipefail
source /opt/ros/${ROS_DISTRO:-jazzy}/setup.bash
source /opt/openvins_ws/install/setup.bash

CONFIG=${OPENVINS_CONFIG:-euroc_mav}
CONFIG_PATH=${OPENVINS_CONFIG_PATH:-}
USE_STEREO=${USE_STEREO:-true}
MAX_CAMERAS=${MAX_CAMERAS:-2}
VERBOSITY=${VERBOSITY:-INFO}

ARGS=(
  config:=${CONFIG}
  use_stereo:=${USE_STEREO}
  max_cameras:=${MAX_CAMERAS}
  verbosity:=${VERBOSITY}
  rviz_enable:=false
)

if [[ -n "${CONFIG_PATH}" ]]; then
  ARGS+=(config_path:=${CONFIG_PATH})
fi

exec ros2 launch ov_msckf subscribe.launch.py "${ARGS[@]}"
